// Code generated by Slice Machine. DO NOT EDIT.

import FooterColumn from './FooterColumn';
import MenuSubTab from './MenuSubTab';

export {
	FooterColumn,
	MenuSubTab,
};

export const components = {
	footer_column: FooterColumn,
	menu_sub_tab: MenuSubTab,
};
